### PR TITLE
tailor the error message to indicate ia Cloudsearch syntax error occurred

### PR DESCRIPTION
**Pull request by DeeNewcum**

### CODE REVIEW

**Comment by Sophira** [comment]
Thanks for the pull request, and I'm sorry I was such a hypocrite when it came to not replying to your Reddit message! I'm not even going to attempt to excuse myself here.

I prefer not using externally-hosted jQuery if I can - I prefer it to be standalone when at all possible (with the exception of any libraries hosted here). Unfortunately, of course, the `:contains()` selector isn't a CSS selector but part of jQuery, so it would need rewritten to use a for loop and the `.match()` function, or something similar.

I realise I'm probably being petty here, though. I'm willing to be swayed if you feel it's worth it. (Part of what was going to be in my message to you was that I didn't know what the revised message should be, which is why I hadn't coded it myself yet. I always like to give other developers credit if I can, though!)

Let me know what you think and if I'm being a bit too petty!

**Comment by DeeNewcum** [comment]
No problem.

I thought you might have an issue with jQuery.  That's fine, I can change it to for-loops.

I do think that jQuery is [easier to read](http://programmers.stackexchange.com/a/141198) and maintain, because it's shorter.  And it's less likely there will be subtle bugs (off-by-one and such).  *shrug*

**Comment by Sophira** [comment]
It can be easier to read, but it's worth remembering that you can still do a lot of the difficult work with [`querySelector`](https://developer.mozilla.org/en-US/docs/Web/API/document.querySelector) and [`querySelectorAll`](https://developer.mozilla.org/en-US/docs/Web/API/document.querySelectorAll). For example, you can select the .md DIV using the first part of your initial selector:

``` javascript
var md = document.querySelector("div.infobar div.md");
```

When I discovered these functions, it was amazing - I didn't even realise that the DOM had these natively, I had always assumed it was a jQuery thing. :D

**Comment by Sophira** [comment]
~~Urgh, sorry for the errors in the comment above. Unfortunately I'm also using an old browser that GitHub no longer supports, so I can't edit or delete the comment. I really should upgrade.~~

~~You get the idea, though!~~

[edit: Updated browser, so I edited the comment.]

**Comment by Sophira** [comment]
Ah, I was going to do the RES module work once this pull request was done, but this works too! I was just checking in to see how things were going, but I guess you're working on this now? I can finish the work on this pull request, I just didn't know if anything was happening or not.

**Comment by Sophira** [comment]
I'll go ahead and work from your commit and do this without jQuery. Hopefully this is okay!

**Comment by Sophira** [comment]
I went ahead and merged your code (b304f6e, which uses your commit ffcc3d8 as a parent) and then rewrote it in 09825da so that it didn't use jQuery. In the process I also expanded the error message slightly (it links to your reference page now, as well as showing what query was used instead), and it'll only show if the cloudsearch checkbox was ticked at the time of the search.

I don't know what you plan to do with the RES code, but it might be worth putting that in a new pull request rather than using this one. I'll leave it open for now until you decide what you want to do!

**Comment by DeeNewcum** [comment]
Sorry, things have been busy at home.

That looks great. :)  You're right, it didn't take much more code to do it without jQuery.

**Comment by DeeNewcum** [comment]
==== Chrome ====

I did figure out how to make this work in Greasemonkey + Chrome, so I'll send a fix for that soon.

==== RES module ====

I briefly looked into making this a RES module.  I'll note that jQuery is bundled with RES, so jQuery would be available at that point.

Anyway, once this is a RES module, it's basically a full-fledged plugin, and I'm not very familiar with debugging full plugins. I haven't progressed beyond that yet.

Yeah, the RES module work can be done in a different pull request.  Thanks!

**Pull request closed without merging**
